version: '3.8'

services:
  server:
    container_name: server
    hostname: server
    image: python:3-alpine
    mac_address: "02:42:ac:11:00:cc"
    cap_add:
      - NET_ADMIN
    command: |
      sh -c "apk add --no-cache bash && 
      python -c '
      from http.server import BaseHTTPRequestHandler, HTTPServer

      class MyHandler(BaseHTTPRequestHandler):
          def do_GET(self):
              self.send_response(200)
              self.send_header(\"Content-type\", \"text/plain\")
              self.end_headers()
              self.wfile.write(b\"Hi I am the server\")
      
      server = HTTPServer((\"\", 80), MyHandler)
      server.serve_forever()
      '"
    networks:
      mitmnet:
        ipv4_address: 192.168.90.100

  client:
    container_name: client
    hostname: client
    image: alpine
    mac_address: "02:42:ac:11:00:bb"
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "apk add --no-cache curl bash && 
      while true; do 
        curl -s -i http://192.168.90.100;
        sleep 7;
      done"
    networks:
      mitmnet:
        ipv4_address: 192.168.90.101

  attacker:
    container_name: attacker
    hostname: attacker
    image: flipperlolli/attacker:latest
    mac_address: "02:42:ac:11:00:aa"
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    entrypoint: /bin/bash -c "echo 'PS1=\"attacker:/# \"' >> /root/.bashrc && /bin/bash"
    networks:
      mitmnet:
        ipv4_address: 192.168.90.102

networks:
  mitmnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
